### ISSUE TITLE
Please teach me ... How to use this package?

### ISSUE THREAD

**Issue by commanderinchief** [weboAp/Visitor#11]
Hi. Sir ..
I'm new to laravel and don't know too much.
Please give me (teach me) simple code to show the counter in my blade.
Thank you . Sir.

**Comment by weboAp** [comment]
sure! did you follow the installation instructions in the read me file ? where are you stuck? let me know how i can contact you will be more than happy to help!

**Comment by mfmsaadi** [comment]
simple code to show the counter in the view (blade) after you're done setting up the package:
first you have to log the visits, you can do so by using this code line into your welcome/index route or method/fubction : Visitor::log(); 
After that you can see the counter by using(ex) :
<h1> {{ Visitor::count() }} </h1>
