### ISSUE TITLE
Location not working

### ISSUE THREAD

**Issue by sunnyjayjay** [weboAp/Visitor#12]
Using Laravel 5, Have put the GeoLite2-City.mmdb file into storage/geo and checked that config/visitor.php points to it. Visitors are logged to the table but the country field is null.

**Comment by weboAp** [comment]
please confirm that you are not  testing from your localhost? you need to be visiting the website from a public ip, for the package to find the origin if available in the GeoLite2-City.mmdb.
let me know.

**Comment by sunnyjayjay** [comment]
You are correct. Apologies. On the production server it is working fine.
