### ISSUE TITLE
Daily visitor

### ISSUE THREAD

**Issue by vtxmg** [weboAp/Visitor#15]
I find it very simple n suitable for me though I need a lil bit more information through it. I need daily page visit if possible plz provide this feature. Currently if someone visit the page it create a record if there is no ip otherwise it increment the hits value, now if it check the created date as well and create new record for the new date I think it is possible what I need. Yes it makes large data record than previous but It will help me a lot.

**Comment by weboAp** [comment]
Are you looking for the count the ips records that was updated certain date eg: today ?  It should give you the number of todays visits
