### ISSUE TITLE
please help me, i have a trouble

### ISSUE THREAD

**Issue by tangyus** [weboAp/Visitor#18]
when i try to use 
#### `Visitor::log();`
and i get a exception.

**Non-static method Weboap\Visitor\Visitor::log() should not be called statically.** 

could help me?

**Comment by tangyus** [comment]
my laravel version is 5.5

**Comment by tangyus** [comment]
#### i try `use Visitor; // package of facade...`

#### but i can not find this `package facade, only VisitorFacade // package of Weboap\Visitor\Facades\VisitorFacade!!!`

#` \Weboap\Visitor\VisitorServiceProvider::class,` in config/app.php

`use Weboap\Visitor\Facades\VisitorFacade;`

```
public function index(Request $request, VisitorFacade $visitor, $id)
{
        $visitor->log();

        ......
}
```
**new exception 
Call to undefined method Weboap\Visitor\Facades\VisitorFacade::log()**

**Comment by weboAp** [comment]
sorry for the delay, you should be able to use 
`use Vistor;
Visitor::log()`

the Facade Visitor is registering automatically withing the service provider registered at the config.php
let me know.

**Comment by Naveedali1234** [comment]
can we use Mysql database for this package?? if yes then how can we use that? please hel me out with this.

Kind regards

**Comment by weboAp** [comment]
yes, it requires MySQL to function properly,  also built to function within laravel framework, 
just add it to your  laravel 5.5 and higher composer.json.. (composer require weboap/visitor ), then configure your config/database.php from that point you can follow the instructions in the read me file,
php artisan vendor:publish to publish the migration of visitor_registery table,
php artisan migrate to migrate the table to your database,
at that point you are ready to go
Visitor::log();   //log in db visitor ip, geo location, hit counter....
see Usage section of the read me file.

**Comment by Naveedali1234** [comment]
yes i have implemented it yesterday, actually i was using localhost and i forgot to comment the value "localhost" in the 'ignored' array, and it works for the localhost also for now.
it's working great.
thanks alot #weboAp
