### ISSUE TITLE
error in orderBy method

### ISSUE THREAD

**Issue by vtxmg** [weboAp/Visitor#5]
Hi Everyone!! I've just updated visitor dependency and got this error:

code:
````
$visitor->all()->orderBy('clicks','desc')->orderBy('updated_at','desc')->paginate(25)
````
error:
````
Call to a member function orderBy() on array
````

The previous version return laravel compatible collection now it returns records in array !!! 
How can I get collection instead of array?????

**Comment by weboAp** [comment]
you was able to do that as the api returned an eloquent collection,
now the new version v2.0.2 return an array, or a simple laravel collection if you do Visitor::all(true);

http://laravel.com/api/master/Illuminate/Support/Collection.html#method_sortBy

let me know if this help.
