### ISSUE TITLE
Non-static method

### ISSUE THREAD

**Issue by kris-terziev** [weboAp/Visitor#8]
Hello,

The package looks great but i get this error:

Non-static method should not be called statically.

**Comment by weboAp** [comment]
can you post more info about the error so i can troubleshoot it? thanks

**Comment by cihadturhan** [comment]
Same problem here. Here is a simple code so you can know the issue

```php

<?php
use Weboap\Visitor\Visitor;

class Log
{   
    public function test(){
        Visitor::log();
    }

}
```

**Comment by weboAp** [comment]
replace the statement  
use Weboap\Visitor\Visitor; 
 with
use Visitor; // the package Facade.
Let me know.
