### ISSUE TITLE
Country not set

### ISSUE THREAD

**Issue by Tiaan1** [weboAp/Visitor#9]
Hi im having issues with the country, it will set the IP correctly but the country in database is Null? Using laravel 5.2

**Comment by weboAp** [comment]
just to confirm, did you downloaded the maxmind geo database (step 5 of the install) and put it in a folder  /storage/geo ? the package basically check the ip address of  the visitor against the maxmind geo db, to set the country code.
let me know.

**Comment by Tiaan1** [comment]
That is correct yes, i have downloaded the file from their website and placed it in storage/geo but still nothing. I'm not sure if this could be a localhost issue. but i doubt.

**Comment by weboAp** [comment]
is the app still hosted on your localhost? if that's the case the IP address the package is registering is the 127.0.0.1 which don't have a country code!  one way of checking is to register manually a fake record in your db with your ISP public ip address and check what code it's the code it's gonna show when you do dd(Visitor:get( your ISP IP address)) ! 
let me know

**Comment by SAIBA0011** [comment]
Yes that is correct, i think the issue is possibly localhost, i will check it out and let you know. Thanks for the support :)

**Comment by Tiaan1** [comment]
Yes that is correct, i think the issue is possibly localhost, i will check it out and let you know. Thanks for the support :)
